### PR TITLE
Update Visual Studio projects to 2015

### PR DESCRIPTION
**Pull request by wiiaboo**
Needs united opus.vcxproj merged for the autobuild to work.

### CODE REVIEW

**Comment by rillian** [comment]
What are you doing for openssl support?

**Comment by wiiaboo** [comment]
atm nothing, did the VS2010 projects support it?
OpenSSL pre-compiled files can probably be used instead of building it.

**Comment by rillian** [comment]
Ok, so that's just not supported yet. If we're downloading and building opus and ogg from git, might as well do that with openssl too? Should probably be a separate pr though if support is new.

**Comment by rillian** [comment]
Merged in 586d32502ecfac3043fa7cadd2ace34da52578ca.

**Comment by wiiaboo** [comment]
Easy enough to add OpenSSL to appveyor, but configuring opusfile to use it is beyond me: https://github.com/wiiaboo/opusfile/commit/31d2ee9280116c73709d83af962d0cadb31a7076

**Pull request closed without merging**
