### PR TITLE
Fix include path of opus_multistream.h

### PR DESCRIPTION
**Pull request by wegylexy**

### CODE REVIEW

**Comment by rillian** [comment]
Please say in your commit message why it's incorrect. Also, the appveyor build disagrees with your change.

**Comment by wegylexy** [comment]
`opus_multistream.h` is installed to `/usr/local/include/opus` on Ubuntu. Perhaps the Visual C++ project has a bad include path too.

**Comment by wegylexy** [comment]
Well, I can add `/usr/local/include/opus` to the include paths in my project.

**Comment by rillian** [comment]
> Well, I can add `/usr/local/include/opus` to the include paths in my project.

Ok, good. That is the intended approach with the opus library headers.

**Comment by braindigitalis** [comment]
ive raised another version of this pr.
why?
Because directly above the erroring line you do:
```cpp
# include <ogg/ogg.h>
```
If you're supposed to include libraries this way, then why isnt this <ogg.h> and why aren't we adding /usr/include/ogg to includes to? I can't find *any* reference to "this is how youre supposed to do it" anywhere in the opus manual. And, i've checked through a lot of it.

Is the project alive though? Seems there are open PRs going back to 2017.

**Comment by Jaskowicz1** [comment]
> Please say in your commit message why it's incorrect. Also, the appveyor build disagrees with your change.

The CI failed because your includes for CMake are wrong. When this corrected the `#include`, your CI was already in opus, so it did `opus/opus/opus_multistream.h`. If you look above to @braindigitalis 's comment, you'll notice how you already include ogg, but never define the include for this in your CMakeLists.txt.

Please look to correct your CMakeLists.txt (along with any other files that may need to be changed to stop going inside `/usr/local/include/opus`) so that you can include opus correctly, meaning other projects do not need to bend to workarounds just so this library can compile.

**Pull request closed without merging**
